name: Deploy to S3 with Approval

on:
  push:
    branches:
      - main

jobs:
  deploy-staging:
    name: Deploy to Staging S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials for staging
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to staging S3 bucket
        run: |
          aws s3 cp index.html s3://${{ secrets.STAGING_S3_BUCKET }}/index.html
          echo "✅ Successfully deployed to staging bucket: ${{ secrets.STAGING_S3_BUCKET }}"

      - name: Output staging URL
        run: |
          echo "🌐 Staging URL: https://${{ secrets.STAGING_S3_BUCKET }}.s3.${{ secrets.AWS_REGION }}.amazonaws.com/index.html"

  wait-for-approval:
    name: Wait for Manual Approval
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment:
      name: production
      url: https://${{ secrets.STAGING_S3_BUCKET }}.s3.${{ secrets.AWS_REGION }}.amazonaws.com/index.html

    steps:
      - name: Approval checkpoint
        run: |
          echo "🚀 Staging deployment completed successfully!"
          echo "📋 Manual approval required to proceed to production deployment."
          echo "🌐 Staging URL: https://${{ secrets.STAGING_S3_BUCKET }}.s3.${{ secrets.AWS_REGION }}.amazonaws.com/index.html"
          echo "👆 Click the URL above to review the staging deployment."
          echo "✅ This job will wait until someone approves the deployment in GitHub."

  deploy-production:
    name: Deploy to Production S3
    runs-on: ubuntu-latest
    needs: wait-for-approval

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials for production
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to production S3 bucket
        run: |
          aws s3 cp index.html s3://${{ secrets.PRODUCTION_S3_BUCKET }}/index.html
          echo "✅ Successfully deployed to production bucket: ${{ secrets.PRODUCTION_S3_BUCKET }}"

      - name: Output production URL
        run: |
          echo "🌐 Production URL: https://${{ secrets.PRODUCTION_S3_BUCKET }}.s3.${{ secrets.AWS_REGION }}.amazonaws.com/index.html"
          echo "🎉 Deployment completed successfully!"
